#site_name: 智算云途 by SElab-Algorithm Group 
# 项目信息
site_name: 智算云途 by SElab-AG # 项目名称
site_url:  https://www.selab-aig.top
site_url:  https://www.selab-ag.top
site_author: SElab-AG
# github 仓库链接
repo_url: https://github.com/Ar-Gas/selab-aig.github.io
repo_name: 智算云途 By SElab

# 导航栏
# 这个功能可以自定义导航栏（顺序 和 内容）
nav: 
  - 新闻:
    - 最新新闻: 新闻/2023-2024-year.md  #.md文件的相对路径
  - 语法:
    - 语法介绍: 语法/1.md
    - c++快速入门: 语法/c++快速入门/入门.md 
  - 算法:
    - 基础算法: 算法/基础算法/1.md
    - 进阶算法: 算法/进阶算法/进阶算法.md
    - 面试算法: 
      - 目录: 算法/面试算法/面试算法目录.md
      - LeetCode Hot: 
        - 两数之和(easy): 算法/面试算法/LeetCode Hot 100/两数之和.md
      - 剑指Offer: 算法/面试算法/剑指offer/1.md
  - 比赛:
    - 比赛介绍&时间: 比赛/比赛时间.md
    - 真题题解:
      - ICPC: 比赛/真题题解/ICPC/2024-ICPC-预选赛.md
      - 蓝桥杯: 比赛\真题题解\蓝桥杯比赛/真题题解/蓝桥杯/蓝桥杯/C++.md
  - 题单:
    - 题单介绍: 题单/1.md
  - 关于我们:
    - 算法组介绍: 关于我们/intro.md


# 主题
theme:
  name: material
  logo: images/智算云途logo.png
  favicon: images/智算云途logo.png
  palette:
    primary: indigo
    accent: indigo
  
  # github 图标
  icon: 
    repo: fontawesome/brands/github
  
  # 导航功能

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expand
    - navigation.path
#    - toc.integrate 

# 页脚
copyright: Copyright &copy; 2022~2024 TYUT-SElab-AG Rights Reserved.
generator: true  #删除页脚显示“使用 MkDocs 材料制造”

# Cookies
consent:
   title: Cookie consent
   description: >- 
     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
     如果你同意,你可以帮助我们让我们的网站更好
